from . import alcance
from . import periodo
from . import emision
from . import actividad
from . import registro
from . import reporte
from . import fuente_externa  
from . import hr_expense_inheritance
from . import compensacion